[platformio]
src_dir = .

[env:genericSTM32H750VB]
platform = ststm32
board = genericSTM32H750VB
framework = stm32cube

upload_protocol = stlink
debug_tool = stlink
debug_speed = 100


upload_command =
    C:/Users/rheas/.platformio/packages/tool-openocd/openocd/tool-openocd/bin/openocd
    -s C:/Users/rheas/.platformio/packages/tool-openocd/openocd//tool-openocd/scripts
   ; -f interface/stlink.cfg
    -c "transport select dapdirect_swd"
    -f target/stm32h7x.cfg
    -c "adapter speed 100"
    -c "adapter driver cmsis-dap"
   ; -c "program {$SOURCE} verify reset exit"

debug_server =
    $PROJECT_PACKAGES_DIR/tool-openocd/bin/openocd
    -s $PROJECT_PACKAGES_DIR/tool-openocd/scripts
    -f interface/stlink.cfg
    -c "transport select dapdirect_swd"
    -f target/stm32h7x.cfg
    -c "adapter speed 100"
    -c "adapter driver cmsis-dap"

build_flags =
    -ICANLib/rocketlib/include
    -ICANLib/message
    -ICANLib
    -ICore/Inc
    -IDrivers/CMSIS/Device/ST/STM32H7xx/Include
    -IDrivers/CMSIS/Include
    -IDrivers/CMSIS/DAP/Source
    -IMiddlewares/Third_Party/FatFs/src
    -IFATFS/Target
    -IFATFS/App

build_src_filter =
    +<Core/Src/*.c>
    +<Core/Src/*.s>
    +<FATFS/App/*.c>
    +<FATFS/Target/*.c>
    +<Middlewares/Third_Party/FatFs/src/*.c>