[platformio]
src_dir = .

[env:genericSTM32H750VB]
platform = ststm32@19.4.0
platform_packages =
   toolchain-gccarmnoneeabi@1.140201.0
board = genericSTM32H750VB
framework = stm32cube

upload_protocol = stlink
debug_tool = stlink
debug_speed = 100
board_build.ldscript = STM32H750VBTX_FLASH.ld


build_flags =
    -ICore/Inc
    -IDrivers/CMSIS/Device/ST/STM32H7xx/Include
    -IDrivers/CMSIS/Include
    -Icanlib/rocketlib/include
    -Icanlib/message
    -Icanlib
    -Icanlib/stm32h7
    ;-IDrivers/STM32H7xx_HAL_Driver/Src
    ;-IDrivers/STM32H7xx_HAL_Driver/Inc/
    -IMiddlewares/Third_Party/FatFs/src
    -IFATFS/Target
    -IFATFS/App

build_src_filter =
    +<Core/Src/*.c>
    +<Core/Src/*.s>
    +<Drivers/CMSIS/Device/ST/STM32H7xx/Include/*>
    +<Drivers/CMSIS/Include/*>
    +<canlib/rocketlib/include/*.h>
    +<canlib/message/*>
    +<canlib/*>
    +<canlib/stm32h7/*>
    +<FATFS/App/*.c>
    +<FATFS/Target/*.c>
    +<Middlewares/Third_Party/FatFs/src/*.c>
    -<canlib/rocketlib/include/pic18f26k83/*>
    -<canlib/rocketlib/include/stm32h7/*>
    -<canlib/rocketlib/rockettest/*>
    -<canlib/rocketlib/tests/*>
    -<canlib/rocketlib/stm32h7/*>
    -<canlib/rocketlib/pic18f26k83/*>
    -<canlib/dspic33e/*>
    -<canlib/pic18f26k83/*>
    -<canlib/mcp2515/*>
    -<canlib/tests/*>
    
    ;+<Drivers/STM32H7xx_HAL_Driver/Src/*>
    ;+<Drivers/STM32H7xx_HAL_Driver/Inc/>
    