[platformio]
src_dir = .

[env:genericSTM32H750VB]
platform = ststm32
board = genericSTM32H750VB
framework = stm32cube

build_flags =
    -ICore/Inc
    -IDrivers/CMSIS/Device/ST/STM32H7xx/Include
    -IDrivers/CMSIS/Include
    -IMiddlewares/Third_Party/FatFs/src
    -IFATFS/Target
    -IFATFS/App

build_src_filter =
    +<Core/Src/*.c>
    +<Core/Src/*.s>
    +<FATFS/App/*.c>
    +<FATFS/Target/*.c>
    +<Middlewares/Third_Party/FatFs/src/*.c>