################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src/SPI \
Core/Src \
Core/Startup \
Drivers/CMSIS/Core/Template/ARMv8-M \
Drivers/CMSIS/Core_A/Source \
Drivers/CMSIS/DAP/Firmware/Source \
Drivers/CMSIS/DSP/ComputeLibrary/Source \
Drivers/CMSIS/DSP/Examples/ARM/arm_bayes_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_bayes_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_bayes_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_bayes_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_bayes_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_bayes_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_svm_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_svm_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_svm_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_svm_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_svm_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_svm_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example \
Drivers/CMSIS/DSP/Source/BasicMathFunctions \
Drivers/CMSIS/DSP/Source/BayesFunctions \
Drivers/CMSIS/DSP/Source/CommonTables \
Drivers/CMSIS/DSP/Source/ComplexMathFunctions \
Drivers/CMSIS/DSP/Source/ControllerFunctions \
Drivers/CMSIS/DSP/Source/DistanceFunctions \
Drivers/CMSIS/DSP/Source/FastMathFunctions \
Drivers/CMSIS/DSP/Source/FilteringFunctions \
Drivers/CMSIS/DSP/Source/InterpolationFunctions \
Drivers/CMSIS/DSP/Source/MatrixFunctions \
Drivers/CMSIS/DSP/Source/QuaternionMathFunctions \
Drivers/CMSIS/DSP/Source/SVMFunctions \
Drivers/CMSIS/DSP/Source/StatisticsFunctions \
Drivers/CMSIS/DSP/Source/SupportFunctions \
Drivers/CMSIS/DSP/Source/TransformFunctions \
Drivers/CMSIS/Device/ST/STM32H7xx/Source/Templates/arm \
Drivers/CMSIS/Device/ST/STM32H7xx/Source/Templates/gcc \
Drivers/CMSIS/Device/ST/STM32H7xx/Source/Templates/iar \
Drivers/CMSIS/Device/ST/STM32H7xx/Source/Templates \
Drivers/CMSIS/NN/Source/ActivationFunctions \
Drivers/CMSIS/NN/Source/BasicMathFunctions \
Drivers/CMSIS/NN/Source/ConcatenationFunctions \
Drivers/CMSIS/NN/Source/ConvolutionFunctions \
Drivers/CMSIS/NN/Source/FullyConnectedFunctions \
Drivers/CMSIS/NN/Source/NNSupportFunctions \
Drivers/CMSIS/NN/Source/PoolingFunctions \
Drivers/CMSIS/NN/Source/ReshapeFunctions \
Drivers/CMSIS/NN/Source/SVDFunctions \
Drivers/CMSIS/NN/Source/SoftmaxFunctions \
Drivers/CMSIS/RTOS2/Source \
Drivers/CMSIS/RTOS2/Template \
Drivers/STM32H7xx_HAL_Driver/Src \
FATFS/App \
FATFS/Target \
Middlewares/Third_Party/FatFs/src \
Middlewares/Third_Party/FatFs/src/option \

